language: node_js
node_js:
  - "0.12"
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
    - NPM_CONFIG_PROGRESS="false"
